### ISSUE TITLE
 Time Sync Command Failure - Failed to set node Time

### ISSUE THREAD

**Issue by fnordspace** [qubic/qubic-cli#51]
## Description
The `synctime` command is failing during the time setting phase while the time query functionality remains operational. The error manifests as "Failed to set node time!" in the CLI output. Since an older version of qubic-cli works it should be no problem with the core code. but qubic-cli itself.

## Technical Analysis
The failure occurs due to a communication breakdown in the response handling:

1. The time query portion executes successfully
2. During time setting, a `logic_error` is thrown at https://github.com/qubic/qubic-cli/blob/eebae073d1e622bfe7b3a45fdd189fbb68f514e5/nodeUtils.cpp#L1303-L1311
  
3. The error stems from `receiveData()` returning -1 at https://github.com/qubic/qubic-cli/blob/eebae073d1e622bfe7b3a45fdd189fbb68f514e5/connection.cpp#L143-L151

This indicates no response is being received from the node.

## Regression Timeline
The issue can be traced through the following commits:

1. `957f87`: First commit with `No connection` error. Before that commit, it works
2. `4c4f9f9`: Introduced build issues (missing qvault.cpp), unrelated.
4. `994bc1`: Introduced the "Failed to set node time" error

## Steps to Reproduce
1. Execute the time sync command
2. Time query succeeds
3. Time setting fails with "Failed to set node time!" error

**Comment by Franziska-Mueller** [comment]
Fixed by @krypdkat in #53
